package com.example.apihermandad.application.services;

import com.example.apihermandad.application.dto.ChangePasswordDto;
import com.example.apihermandad.application.dto.UsuarioCreateDto;
import com.example.apihermandad.application.dto.UsuarioDto;
import com.example.apihermandad.application.dto.UsuarioSelfUpdateDto;
import com.example.apihermandad.application.events.UsuarioCreadoEvent;
import com.example.apihermandad.application.mapper.UsuarioMapper;
import com.example.apihermandad.domain.entity.Usuario;
import com.example.apihermandad.domain.repository.SesionRepository;
import com.example.apihermandad.domain.repository.UsuarioRepository;

import com.example.apihermandad.utils.HttpMessage;
import com.example.apihermandad.utils.PasswordManager;

import org.springframework.context.ApplicationEventPublisher;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;

@Service
public class UsuarioService {
    private final UsuarioRepository userRepository;
    private final UsuarioMapper userMapper;
    private final PasswordEncoder passwordEncoder;
    private final SesionRepository sesionRepository;
    private final ApplicationEventPublisher applicationEventPublisher;


    UsuarioService(UsuarioRepository userRepository, UsuarioMapper userMapper, PasswordEncoder passwordEncoder,
            SesionRepository sesionRepository, ApplicationEventPublisher applicationEventPublisher) {
        this.userRepository = userRepository;
        this.userMapper = userMapper;
        this.passwordEncoder = passwordEncoder;
        this.sesionRepository = sesionRepository;
        this.applicationEventPublisher = applicationEventPublisher;
    }

    public List<UsuarioDto> findAll() {
        return userRepository.findAll()
                .stream()
                .map(userMapper::toDto)
                .toList();
    }

    public UsuarioDto findById(Integer id) {
        return userRepository.findById(id)
                .map(userMapper::toDto)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        HttpMessage.NOT_FOUND_USSER));
    }

    @Transactional
    public UsuarioDto create(UsuarioCreateDto dto) {
        String autogeneratedPassword = PasswordManager.generatePassword();
        dto.setPassword(autogeneratedPassword);

        Usuario user = userMapper.toCreateEntity(dto);
        userRepository.save(user);

        applicationEventPublisher.publishEvent(new UsuarioCreadoEvent(dto));

        return userMapper.toDto(user);
    }

    public UsuarioDto updateSelf(Integer id, UsuarioSelfUpdateDto dto) {
        Usuario user = userRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        HttpMessage.NOT_FOUND_USSER));
        user.setEmail(dto.getEmail());
        user.setPhone(dto.getPhone());
        user.setAddress(dto.getAddress());

        return userMapper.toDto(userRepository.save(user));

    }

    @Transactional
    public UsuarioDto update(Integer id, UsuarioDto dto) {

        Usuario usuario = userRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        HttpMessage.NOT_FOUND_USSER));

        usuario.setName(dto.getName());
        usuario.setDni(dto.getDni());
        usuario.setAddress(dto.getAddress());
        usuario.setPhone(dto.getPhone());
        usuario.setEmail(dto.getEmail());
        usuario.setRole(dto.getRole());
        usuario.setActive(dto.getActive());

        return userMapper.toDto(userRepository.save(usuario));
    }

    public void invalidate(Integer id) {
        Usuario user = userRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        HttpMessage.NOT_FOUND_USSER));

        user.setActive(false);
        userRepository.save(user);
    }

    @Transactional
    public void changePassword(
            Integer authenticatedUserId,
            ChangePasswordDto dto) {

        Usuario user = userRepository.findById(authenticatedUserId)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        HttpMessage.NOT_FOUND_USSER));

        if (!passwordEncoder.matches(dto.oldPassword(), user.getPassword())) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "La contraseña actual no es correcta");
        }

        if (!dto.newPassword().equals(dto.confirmPassword())) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "La nueva contraseña no coincide");
        }

        if (passwordEncoder.matches(dto.newPassword(), user.getPassword())) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "La nueva contraseña no puede ser igual a la anterior");
        }

        user.setPassword(passwordEncoder.encode(dto.newPassword()));
        userRepository.save(user);

        sesionRepository.invalidateAllByUserId(user.getId());
    }

}
